package ch.unil.softarch.luxurycarrental.domain.entities;

import ch.unil.softarch.luxurycarrental.domain.enums.DriveType;
import ch.unil.softarch.luxurycarrental.domain.enums.Transmission;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

import java.io.Serializable;
import java.util.List;
import java.util.UUID;

/**
 * Represents a specific type/model of a car (e.g., "Toyota RAV4").
 * <p>
 * This entity defines the static specifications of a car model,
 * which can be shared by multiple physical Car instances.
 * </p>
 */
@Entity
@Table(name = "car_type")
public class CarType implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    @Column(length = 36)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private UUID id;  // Unique identifier

    @Column(nullable = false)
    private String category;  // Car category (e.g., SUV, Sport)

    @Column(nullable = false)
    private String brand;  // Brand (e.g., Toyota)

    @Column(nullable = false)
    private String model;  // Model (e.g., RAV4)

    private String engine;  // Engine specifications

    private int power;  // Power [hp]

    private int maxSpeed;  // Maximum speed [km/h]

    private double acceleration;  // 0-100 km/h acceleration [s]

    private double weight;  // Weight [kg]

    @Enumerated(EnumType.STRING)
    private DriveType driveType;  // Drive type (e.g., 4WD)

    @Enumerated(EnumType.STRING)
    private Transmission transmission;  // Transmission type (e.g., Automatic)

    private int seats;  // Number of seats

    @Column(length = 1000)
    private String description;  // Detailed description

    @ElementCollection
    @CollectionTable(name = "car_type_features", joinColumns = @JoinColumn(name = "car_type_id"))
    @Column(name = "feature")
    private List<String> features;  // List of features (e.g., GPS, Bluetooth)

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-arg constructor required by JPA.
     */
    public CarType() {
        // ID generation handled by @PrePersist
    }

    /**
     * Constructor with specifications.
     * Note: ID is auto-generated by lifecycle callbacks.
     */
    public CarType(String category, String brand, String model, String engine,
                   int power, int maxSpeed, double acceleration, double weight,
                   DriveType driveType, Transmission transmission,
                   int seats, String description, List<String> features) {
        // Removed explicit ID parameter
        this.category = category;
        this.brand = brand;
        this.model = model;
        this.engine = engine;
        this.power = power;
        this.maxSpeed = maxSpeed;
        this.acceleration = acceleration;
        this.weight = weight;
        this.driveType = driveType;
        this.transmission = transmission;
        this.seats = seats;
        this.description = description;
        this.features = features;
    }

    // -------------------------------------------------------------------------
    // Lifecycle Callbacks
    // -------------------------------------------------------------------------

    /**
     * Executed automatically before persisting to the database.
     * Generates a UUID if one doesn't exist.
     */
    @PrePersist
    protected void onCreate() {
        if (this.id == null) {
            this.id = UUID.randomUUID();
        }
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getBrand() { return brand; }
    public void setBrand(String brand) { this.brand = brand; }

    public String getModel() { return model; }
    public void setModel(String model) { this.model = model; }

    public String getEngine() { return engine; }
    public void setEngine(String engine) { this.engine = engine; }

    public int getPower() { return power; }
    public void setPower(int power) { this.power = power; }

    public int getMaxSpeed() { return maxSpeed; }
    public void setMaxSpeed(int maxSpeed) { this.maxSpeed = maxSpeed; }

    public double getAcceleration() { return acceleration; }
    public void setAcceleration(double acceleration) { this.acceleration = acceleration; }

    public double getWeight() { return weight; }
    public void setWeight(double weight) { this.weight = weight; }

    public DriveType getDriveType() { return driveType; }
    public void setDriveType(DriveType driveType) { this.driveType = driveType; }

    public Transmission getTransmission() { return transmission; }
    public void setTransmission(Transmission transmission) { this.transmission = transmission; }

    public int getSeats() { return seats; }
    public void setSeats(int seats) { this.seats = seats; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public List<String> getFeatures() { return features; }
    public void setFeatures(List<String> features) { this.features = features; }

    // -------------------------------------------------------------------------
    // Overrides
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        return "CarType{" +
                "id=" + id +
                ", category='" + category + '\'' +
                ", brand='" + brand + '\'' +
                ", model='" + model + '\'' +
                ", engine='" + engine + '\'' +
                ", power=" + power +
                ", maxSpeed=" + maxSpeed +
                ", acceleration=" + acceleration +
                ", weight=" + weight +
                ", driveType=" + driveType +
                ", transmission=" + transmission +
                ", seats=" + seats +
                ", description='" + description + '\'' +
                ", features=" + features +
                '}';
    }
}