package ch.unil.softarch.luxurycarrental.domain;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import ch.unil.softarch.luxurycarrental.domain.entities.Admin;

/**
 * Unit tests for the {@link Admin} domain entity.
 * <p>
 * This class verifies the behavior of the Admin POJO (Plain Old Java Object).
 * Since these tests run without a JPA container (database), lifecycle callbacks
 * like @PrePersist do not trigger automatically.
 * </p>
 */
class AdminTest {

    private Admin admin;
    private UUID adminId;

    /**
     * Sets up the test environment before each test method.
     */
    @BeforeEach
    void setUp() {
        adminId = UUID.randomUUID();

        // 1. Initialize Admin using the constructor
        // Note: The constructor does not include the ID anymore, as IDs are typically
        // auto-generated by JPA or set manually during migration.
        admin = new Admin(
                "adminUser",
                "password123",
                "John Doe",
                "admin@example.com"
        );

        // 2. Manually set the ID for testing purposes
        // Rationale: In a standard unit test environment (without a database/EntityManager),
        // the @PrePersist lifecycle callback is NOT triggered. Therefore, the ID is not
        // automatically generated. We must manually invoke setId to simulate the database
        // identity for testing equals/hashCode and getters.
        admin.setId(adminId);
    }

    @Test
    void testGetters() {
        assertEquals(adminId, admin.getId());
        assertEquals("adminUser", admin.getUsername());
        assertEquals("password123", admin.getPassword());
        assertEquals("John Doe", admin.getName());
        assertEquals("admin@example.com", admin.getEmail());

        // 3. Verify that timestamps are null in this environment
        // Note: Without a JPA container, the @PrePersist (onCreate) method is never called.
        // Since the Admin class typically hides setters for createdAt/updatedAt to enforce
        // audit automation, these fields remain null in this isolated unit test.
        assertNull(admin.getCreatedAt(), "createdAt should be null in unit tests without JPA");
        assertNull(admin.getUpdatedAt(), "updatedAt should be null in unit tests without JPA");
    }

    @Test
    void testSetters() {
        // Test setters for mutable functional fields
        admin.setUsername("newUser");
        admin.setPassword("newPass");
        admin.setName("Jane Doe");
        admin.setEmail("jane@example.com");

        assertEquals("newUser", admin.getUsername());
        assertEquals("newPass", admin.getPassword());
        assertEquals("Jane Doe", admin.getName());
        assertEquals("jane@example.com", admin.getEmail());

        // 4. Note on Timestamps:
        // Tests for setCreatedAt and setUpdatedAt are omitted because these setter methods
        // were removed/hidden in the Admin entity to rely on JPA Lifecycle Callbacks.
    }

    @Test
    void testEqualsAndHashCode() {
        // Create another Admin object with the SAME ID but different data
        Admin sameIdAdmin = new Admin("user2", "pass2", "Name2", "email2@example.com");

        // Crucial: Manually set the same ID to verify equality based on identity (Primary Key)
        sameIdAdmin.setId(adminId);

        assertEquals(admin, sameIdAdmin, "Admins with the same ID should be equal");
        assertEquals(admin.hashCode(), sameIdAdmin.hashCode(), "HashCodes should match for same ID");

        // Create an Admin object with a DIFFERENT ID
        Admin differentAdmin = new Admin("adminUser", "password123", "John Doe", "admin@example.com");

        // Set a randomly generated different ID
        differentAdmin.setId(UUID.randomUUID());

        assertNotEquals(admin, differentAdmin, "Admins with different IDs should not be equal");
    }

    @Test
    void testToString() {
        String str = admin.toString();

        // Verify that key information is present in the string representation
        assertTrue(str.contains(adminId.toString()));
        assertTrue(str.contains("adminUser"));
        assertTrue(str.contains("John Doe"));
        assertTrue(str.contains("admin@example.com"));
    }
}